"""Re-export focused Curator core models for compatibility."""

from curator.core.models.base import CuratorModel
from curator.core.models.goals import (
    GoalAcceptance,
    GoalApprovalGate,
    GoalContract,
    GoalCriterion,
    GoalRevisionRecord,
    GoalRunRecord,
    GoalVerification,
)
from curator.core.models.harness import (
    EngineerImplementationOutput,
    HarnessRunResult,
    HarnessRunSpec,
    PMConfirmationOutput,
    PMPlanOutput,
    ProviderRunResult,
    QAValidationOutput,
)
from curator.core.models.init import InitProposal
from curator.core.models.loops import (
    CompiledLoopPlan,
    CompiledLoopStep,
    DoneCriteria,
    EvidenceRef,
    GuideRef,
    LoopContract,
    LoopDecisionRecord,
    LoopIterationRecord,
    LoopRunRecord,
    LoopTemplate,
    SensorRef,
)
from curator.core.models.paths import CuratorPaths
from curator.core.models.roles import (
    RoleCollaborator,
    RoleContract,
    RoleHandoffRule,
    RoleSelection,
    RoleSelectionRecord,
)
from curator.core.models.runtime import (
    ApprovalDecisionRecord,
    ApprovalRequestRecord,
    AssignmentRecord,
    ContextPackageRecord,
    DiscoverySessionRecord,
    DiscussionTurnRecord,
    GoalDraftRecord,
    MemoryEntryRecord,
    PauseRecord,
    ProviderProfileRecord,
    ProviderRunRecord,
    ProviderSessionRecord,
    QuotaStateRecord,
    ResumeEventRecord,
    RoleInstanceRecord,
    RoleProviderBindingRecord,
    WorkItemRecord,
)
from curator.core.models.session import EventRecord, MessageRecord, SessionRecord, TaskRecord
from curator.core.models.snapshot import WorkflowSnapshot

__all__ = [
    "ApprovalDecisionRecord",
    "ApprovalRequestRecord",
    "AssignmentRecord",
    "CuratorModel",
    "CuratorPaths",
    "CompiledLoopPlan",
    "CompiledLoopStep",
    "ContextPackageRecord",
    "DoneCriteria",
    "DiscoverySessionRecord",
    "DiscussionTurnRecord",
    "EngineerImplementationOutput",
    "EventRecord",
    "EvidenceRef",
    "GoalAcceptance",
    "GoalApprovalGate",
    "GoalContract",
    "GoalCriterion",
    "GoalDraftRecord",
    "GoalRevisionRecord",
    "GoalRunRecord",
    "GoalVerification",
    "GuideRef",
    "HarnessRunResult",
    "HarnessRunSpec",
    "InitProposal",
    "LoopContract",
    "LoopDecisionRecord",
    "LoopIterationRecord",
    "LoopRunRecord",
    "LoopTemplate",
    "MemoryEntryRecord",
    "MessageRecord",
    "PMConfirmationOutput",
    "PMPlanOutput",
    "PauseRecord",
    "ProviderProfileRecord",
    "ProviderRunResult",
    "ProviderRunRecord",
    "ProviderSessionRecord",
    "QAValidationOutput",
    "QuotaStateRecord",
    "RoleCollaborator",
    "RoleContract",
    "RoleHandoffRule",
    "RoleInstanceRecord",
    "RoleProviderBindingRecord",
    "RoleSelection",
    "RoleSelectionRecord",
    "ResumeEventRecord",
    "SensorRef",
    "SessionRecord",
    "TaskRecord",
    "WorkflowSnapshot",
    "WorkItemRecord",
]
